title: Yoko's Blog
description: Development Note.
show_downloads: false
google_analytics: false
theme: jekyll-theme-cayman
# 下面放入工程的 _config.yml 文件中
# title: Yoko Blog
# description: Jeecg Development Note.
# remote_theme: yoko-murasame/cayman-yoko
# plugins:
#   - jekyll-remote-theme # add this line to the plugins list if you already have one